@startuml
'https://plantuml.com/sequence-diagram

autonumber

== Suppression d'un formulaire ==
Utilisateur -> Systeme: Démarrage du programme
activate Systeme
Systeme -> Systeme: afficheMenuPrincipal()
Systeme -> Utilisateur: Les différentes options sont affichées sur le terminal
deactivate Systeme

Utilisateur -> Systeme: Tape 4 dans le terminal
activate Systeme
Systeme->Systeme: afficheIdFormulaire()
Systeme->Utilisateur
deactivate Systeme

Utilisateur->Systeme: Rentre l'Id du formulaire souhaité
activate Systeme
Systeme->Systeme: suppressionFormulaire()
Systeme->Utilisateur: Formulaire supprimé avec succès
deactivate Systeme
==Fin==
@enduml