@startuml
'https://plantuml.com/sequence-diagram

autonumber

== Accéder au graphe des étudiants fraudeurs ==

Utilisateur -> Systeme: Démarrage du programme
activate Systeme
Systeme -> Systeme: afficheMenuPrincipal()
Systeme -> Utilisateur: Les différentes options sont affichées sur le terminal
deactivate Systeme

Utilisateur -> Systeme: Tape 3 dans le terminal
activate Systeme
Systeme -> Systeme: afficheMenuRechercheAnalyse()
Systeme -> Utilisateur
deactivate Systeme

Utilisateur -> Systeme: Choisit l'option d'affichage du graphe
activate Systeme
Systeme -> Systeme: afficheGrapheFraudeur()
Systeme -> Utilisateur
deactivate Systeme
== Fin ==

@enduml