@startuml
'https://plantuml.com/sequence-diagram

autonumber

== Initialisation ==

Utilisateur -> Systeme: Démarrage du programme
activate Systeme
Systeme -> Systeme: afficheMenuPrincipal()
Systeme -> Utilisateur
deactivate Systeme

Utilisateur -> Systeme: Tape 1 sur le terminal
activate Systeme
Systeme -> Systeme: afficheCreationFormulaire()
Systeme -> Utilisateur: Formulaire créé avec succès
deactivate Systeme

Utilisateur -> Systeme: Tape 2 sur le terminal
activate Systeme
Systeme -> Systeme: afficheModificationFormulaire()
Systeme -> Utilisateur: Formulaire modifié avec succès
deactivate Systeme

Utilisateur -> Systeme: Tape 3 sur le terminal
activate Systeme
Systeme -> Systeme: afficheRechercheAnalyse()
Systeme -> Utilisateur: Recherche et analyse terminée
deactivate Systeme

Utilisateur -> Systeme: Tape 4 sur le terminal
activate Systeme
Systeme -> Systeme: afficheSuppressionFormulaire()
Systeme -> Utilisateur: Formulaire supprimé avec succès
deactivate Systeme

Utilisateur -> Systeme: Tape 5 sur le terminal
activate Systeme
Systeme -> Systeme: afficheCreationEpreuve()
Systeme -> Utilisateur: Épreuve créée avec succès
deactivate Systeme

Utilisateur -> Systeme: Tape 6 sur le terminal
activate Systeme
Systeme -> Systeme: afficheFinProgramme()
Systeme -> Utilisateur: L'utilisateur a quitté le programme avec succès
deactivate Systeme

== Fin ==

@enduml